version: "3"
services:
  redis:
    image: "redis:4"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: on-failure:5
    volumes:
      - ~/bridge_data/redis:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6379"]
      interval: 1m30s
      timeout: 10s
      retries: 3    
      start_period: 40s
  rabbit:
    image: "rabbitmq:3"
    hostname: rabbit
    environment:
      - RABBITMQ_NODENAME=node@rabbit
    volumes:
      - ~/bridge_data/rabbitmq:/var/lib/rabbitmq/mnesia
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5672"]
      interval: 1m30s
      timeout: 10s
      retries: 3    
      start_period: 40s
    restart: unless-stopped
  bridge:
    build: .
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
    command: "true"
    restart: unless-stopped
