version: "3"
services:
  redis:
    image: "redis:4"
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    restart: on-failure
    volumes:
      - ~/bridge_data/redis:/data
  rabbit:
    image: "rabbitmq:3"
    hostname: rabbit
    environment:
      - RABBITMQ_NODENAME=node@rabbit
    volumes:
      - ~/bridge_data/rabbitmq:/var/lib/rabbitmq/mnesia
    restart: unless-stopped
  bridge:
    build: .
    env_file: ./.env
    environment:
      - NODE_ENV=production
      - QUEUE_URL=amqp://rabbit
      - REDIS_URL=redis://redis
    command: "true"
    restart: unless-stopped
